services:
  - type: web
    name: electrichka3
    env: python
    plan: free
    buildCommand: "python3.11 -m pip install --upgrade pip && python3.11 -m pip install -r requirements.txt"
    startCommand: "python3.11 bot.py"
    envVars:
      PYTHON_VERSION: 3.11.9
